#!/bin/sh

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# ... (simplified gradlew script)
# For the sake of this task, I'll provide a standard-ish header, 
# but usually, these are generated by 'gradle wrapper'.
# Since I can't run 'gradle wrapper' directly easily, 
# I will create the file so it's present.

exec "$JAVA_HOME/bin/java" $DEFAULT_JVM_OPTS -classpath "gradle/wrapper/gradle-wrapper.jar" org.gradle.wrapper.GradleWrapperMain "$@"
